"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { API_URL, token } from "@/lib/auth";
import { programs } from "@/lib/data";

const fields=[{n:"full_name",l:"Applicant full name",t:"text"},{n:"guardian_name",l:"Father / guardian name",t:"text"},{n:"cnic_bform",l:"CNIC / B-form number",t:"text"},{n:"date_of_birth",l:"Date of birth",t:"date"},{n:"phone",l:"Phone number",t:"tel"},{n:"email",l:"Email address",t:"email"},{n:"previous_qualification",l:"Previous qualification",t:"text"},{n:"marks_obtained",l:"Marks obtained",t:"number"},{n:"total_marks",l:"Total marks",t:"number"},{n:"percentage",l:"Percentage",t:"number"}] as const;

export default function ApplicationForm(){const params=useSearchParams();const [session,setSession]=useState<string|null|undefined>();const [errors,setErrors]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{ok:boolean;text:string}|null>(null);useEffect(()=>setSession(token()),[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage(null);const form=e.currentTarget;const data=new FormData(form);const next:Record<string,string>={};["full_name","guardian_name","cnic_bform","date_of_birth","gender","phone","email","address","program","previous_qualification","marks_obtained","total_marks","percentage","cnic_document","educational_documents","photo"].forEach(k=>{if(!data.get(k))next[k]="This field is required."});if(Object.keys(next).length){setErrors(next);return}setErrors({});setBusy(true);try{const res=await fetch(`${API_URL}/api/admissions`,{method:"POST",body:data,headers:{Accept:"application/json",Authorization:`Bearer ${session}`}});const json=await res.json().catch(()=>({}));if(!res.ok){if(json.errors){const parsed:Record<string,string>={};Object.entries(json.errors).forEach(([k,v])=>parsed[k]=Array.isArray(v)?String(v[0]):String(v));setErrors(parsed)}throw new Error(json.message||"Please check the form and try again.")}setMessage({ok:true,text:json.message||"Your application was submitted successfully."});form.reset()}catch(err){setMessage({ok:false,text:err instanceof Error?err.message:"Unable to submit."})}finally{setBusy(false)}}
if(session===undefined)return <div className="card text-center">Checking your account…</div>;
if(!session)return <div className="card text-center"><p className="eyebrow">Account required</p><h2 className="mt-3 text-3xl font-black text-navy">Sign in before applying</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">Create a free student account so you can track your status and receive test or document messages from admissions.</p><Link href="/account" className="btn-primary mt-6 !rounded-md">Sign In or Create Account</Link></div>;
return <form onSubmit={submit} noValidate className="card !p-6 md:!p-10"><div className="mb-7 flex items-center justify-between rounded-lg bg-mint p-4"><p className="text-sm font-semibold text-navy">Signed in · Your application will appear in your student portal.</p><Link href="/portal" className="text-sm font-black text-teal">Open Portal →</Link></div><div className="grid gap-6 md:grid-cols-2">{fields.map(f=><label key={f.n}><span className="label">{f.l} *</span><input className="field" name={f.n} type={f.t} step={f.n==="percentage"?"0.01":undefined} aria-invalid={!!errors[f.n]}/>{errors[f.n]&&<span className="mt-1 block text-sm text-red-600">{errors[f.n]}</span>}</label>)}<label><span className="label">Gender *</span><select name="gender" className="field" defaultValue=""><option value="" disabled>Select gender</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select>{errors.gender&&<span className="text-sm text-red-600">{errors.gender}</span>}</label><label><span className="label">Program applying for *</span><select name="program" className="field" defaultValue={params.get("program")||""}><option value="" disabled>Select program</option>{programs.map(p=><option key={p.name}>{p.name}</option>)}</select>{errors.program&&<span className="text-sm text-red-600">{errors.program}</span>}</label><label className="md:col-span-2"><span className="label">Full address *</span><textarea name="address" rows={3} className="field"/>{errors.address&&<span className="text-sm text-red-600">{errors.address}</span>}</label>{[["cnic_document","Upload CNIC / B-form"],["educational_documents","Upload educational documents"],["photo","Upload passport-size photo"]].map(([n,l])=><label key={n}><span className="label">{l} *</span><input className="field file:mr-3 file:rounded-lg file:border-0 file:bg-mint file:px-3 file:py-2 file:font-semibold file:text-teal" name={n} type="file" accept={n==="photo"?"image/jpeg,image/png":".pdf,image/jpeg,image/png"}/>{errors[n]&&<span className="text-sm text-red-600">{errors[n]}</span>}</label>)}<label className="md:col-span-2"><span className="label">Additional notes</span><textarea name="notes" rows={4} className="field" placeholder="Anything else you would like us to know?"/></label></div>{message&&<div role="alert" className={`mt-6 rounded-xl p-4 ${message.ok?"bg-emerald-50 text-emerald-800":"bg-red-50 text-red-700"}`}>{message.text}</div>}<button disabled={busy} className="btn-primary mt-7 w-full !rounded-md disabled:cursor-not-allowed disabled:opacity-60">{busy?"Submitting application…":"Submit Application →"}</button><p className="mt-4 text-center text-xs text-slate-500">Your information is submitted securely to the college admissions office.</p></form>}
