<?php

namespace App\Services;

use App\Models\Admission;

class AdmissionPdf
{
    public function render(Admission $admission): string
    {
        $lines = [
            'SHAMIM AKHTAR COLLEGE OF NURSING & MIDWIFERY',
            'KORT, MIRPUR, AZAD JAMMU & KASHMIR',
            '',
            'APPLICATION SUMMARY #'.$admission->id,
            'Status: '.strtoupper($admission->status),
            'Submitted: '.$admission->created_at?->format('d M Y, h:i A'),
            '',
            'Applicant: '.$admission->full_name,
            'Father / Guardian: '.$admission->guardian_name,
            'CNIC / B-form: '.$admission->cnic_bform,
            'Date of birth: '.$admission->date_of_birth?->format('d M Y'),
            'Gender: '.ucfirst($admission->gender),
            'Phone: '.$admission->phone,
            'Email: '.$admission->email,
            'Address: '.$admission->address,
            '',
            'Program: '.$admission->program,
            'Previous qualification: '.$admission->previous_qualification,
            'Marks: '.$admission->marks_obtained.' / '.$admission->total_marks,
            'Percentage: '.$admission->percentage.'%',
            'Notes: '.($admission->notes ?: 'None'),
            '',
            'Generated by the SACNM Admissions Portal on '.now()->format('d M Y, h:i A'),
        ];
        $wrapped = [];
        foreach ($lines as $line) array_push($wrapped, ...(strlen($line) ? explode("\n", wordwrap($line, 88, "\n", true)) : ['']));
        $content = "BT\n/F1 10 Tf\n50 790 Td\n14 TL\n";
        foreach ($wrapped as $index => $line) {
            $safe = str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], iconv('UTF-8', 'Windows-1252//TRANSLIT', $line) ?: $line);
            $content .= ($index ? "T*\n" : '')."({$safe}) Tj\n";
        }
        $content .= "ET";
        $objects = [
            '<< /Type /Catalog /Pages 2 0 R >>',
            '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
            '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
            '<< /Length '.strlen($content)." >>\nstream\n{$content}\nendstream",
            '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
        ];
        $pdf = "%PDF-1.4\n"; $offsets = [0];
        foreach ($objects as $i => $object) { $offsets[] = strlen($pdf); $pdf .= ($i + 1)." 0 obj\n{$object}\nendobj\n"; }
        $xref = strlen($pdf); $pdf .= "xref\n0 6\n0000000000 65535 f \n";
        for ($i = 1; $i <= 5; $i++) $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
        return $pdf."trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF";
    }
}
