"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { api, clearToken } from "@/lib/auth";

type Message={id:number;message:string;created_at:string;sender:string};
type Application={id:number;program:string;status:string;submitted_at:string;updated_at:string;messages:Message[]};
const labels:Record<string,string>={pending:"Pending review",under_review:"Under review",documents_required:"Documents required",test_scheduled:"Test scheduled",accepted:"Accepted",rejected:"Not accepted"};

export default function PortalPage(){const [apps,setApps]=useState<Application[]|null>(null);const [error,setError]=useState("");const router=useRouter();useEffect(()=>{api('/api/student/dashboard').then(r=>setApps(r.data)).catch(e=>{if(e.status===401)router.replace('/account');else setError(e.message)})},[router]);async function logout(){await api('/api/auth/logout',{method:'POST'}).catch(()=>{});clearToken();router.push('/account')}
return <section className="section container-pad"><div className="flex flex-col justify-between gap-4 border-b pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow">Student portal</p><h1 className="mt-2 text-4xl font-black text-navy">My applications</h1><p className="mt-2 text-slate-600">Track decisions and messages from the admissions office.</p></div><div className="flex gap-3"><Link href="/apply" className="btn-primary !rounded-md">New Application</Link><button onClick={logout} className="rounded-md border px-5 py-3 font-bold text-navy">Sign Out</button></div></div>{error&&<div className="mt-8 rounded-lg bg-red-50 p-4 text-red-700">{error}</div>}{apps===null&&!error&&<p className="py-16 text-center text-slate-500">Loading your portal…</p>}{apps?.length===0&&<div className="card mt-10 text-center"><h2 className="text-2xl font-black text-navy">No applications yet</h2><p className="mt-2 text-slate-600">Start an application and its progress will appear here.</p><Link href="/apply" className="btn-primary mt-6 !rounded-md">Apply Now</Link></div>}<div className="mt-10 grid gap-7">{apps?.map(item=><article key={item.id} className="card"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-teal">APPLICATION #{item.id}</p><h2 className="mt-1 text-2xl font-black text-navy">{item.program}</h2><p className="mt-2 text-sm text-slate-500">Submitted {new Date(item.submitted_at).toLocaleDateString()}</p></div><span className="rounded-full bg-mint px-4 py-2 text-sm font-black text-navy">{labels[item.status]||item.status}</span></div><div className="mt-7 border-t pt-6"><h3 className="font-black text-navy">Admissions messages</h3>{item.messages.length===0?<p className="mt-3 text-sm text-slate-500">No messages yet.</p>:<div className="mt-4 grid gap-3">{item.messages.map(msg=><div key={msg.id} className="rounded-lg bg-slate-50 p-4"><p className="leading-7 text-slate-700">{msg.message}</p><p className="mt-2 text-xs font-semibold text-slate-500">{msg.sender} · {new Date(msg.created_at).toLocaleString()}</p></div>)}</div>}</div></article>)}</div></section>}
