export type Program={name:string;duration:string;eligibility:string;gender:string;description:string};
export const programs:Program[]=[
{name:"BS Nursing",duration:"4 Year Degree Program",eligibility:"FSc Pre-Medical, minimum 50% marks; age 18–35",gender:"Male & female",description:"A rigorous degree blending nursing science, clinical practice, leadership and compassionate patient care."},
{name:"BS Midwifery",duration:"4 Year Degree Program",eligibility:"FSc Pre-Medical, minimum 50% marks; age 18–35",gender:"Female only",description:"Prepare to provide evidence-based, respectful care to women, newborns and families across the care journey."},
{name:"LHV",duration:"2 Year Diploma",eligibility:"Matric with Science",gender:"Female only",description:"Community-centred training for Lady Health Visitors serving maternal, child and public health needs."},
{name:"CNA",duration:"2 Year Diploma",eligibility:"Matric with Science",gender:"Male & female",description:"Practical preparation in essential bedside support, patient safety and professional healthcare assistance."},
{name:"CMW",duration:"2 Year Diploma",eligibility:"Matric with Science",gender:"Female only",description:"Focused midwifery education for safe maternity care and stronger outcomes in local communities."}
];
export const goals=["Educate and prepare competent professional nurses.","Improve healthcare services in AJK through skilled graduates.","Promote leadership and innovation in nursing practice.","Enhance research culture in nursing education.","Strengthen community-based healthcare services.","Build partnerships with hospitals and health organizations."];
export const objectives=["Deliver safe, holistic, and competent patient care.","Perform essential clinical procedures with accuracy.","Apply infection control and patient safety standards.","Integrate theory with evidence-based practice.","Assess, prioritize, and make sound clinical decisions.","Communicate effectively and uphold professional ethics.","Collaborate within healthcare teams and demonstrate leadership.","Engage in research and lifelong learning.","Promote community health and address public health needs in AJK and beyond."];
